name: upload data to hugging face
on: 
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: false
      - name: Install dependencies
        run: npm install
      - name: Run a overlay analysis script
        run: npx tsx ./uploadDataToHF.ts
        env:
          HF_WRITE_TOKEN: ${{secrets.HF_WRITE_TOKEN}}
          HF_READ_TOKEN: ${{secrets.HF_READ_TOKEN}}
          HF_USERNAME: ${{secrets.HF_USERNAME}}
          LOCAL_BASE_PATH: ${{secrets.LOCAL_BASE_PATH}}

          
