name: index spatial files by ward
on: 
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: false
      - name: Install dependencies
        run: npm install
      - name: Run ward indexing script
        run: npx tsx scripts/wardIndexing.ts
        env:
          HF_WRITE_TOKEN: ${{secrets.HF_WRITE_TOKEN}}
          HF_READ_TOKEN: ${{secrets.HF_READ_TOKEN}}
          HF_USERNAME: ${{secrets.HF_USERNAME}}
          LOCAL_BASE_PATH: ${{secrets.LOCAL_BASE_PATH}}

          
